import os

try:
    configfile_path = config['configfile_path']
except:
    configfile_path = "../config/config.yml"    
configfile: configfile_path

#configfile: "../config/config.yml"

path=config["archived_path"]

query_ids=config["query_ids"]
for query in query_ids:
        if (os.path.isdir(path+"/"+query)):
                #print (query+" already computed");
                query_ids.remove(query);

#print (query_ids)

rule all:
    input:
#        expand("{workdir}/results/{query_id}/5_raxmlng_ancestral_scores/{query_id}_wl_param_{pattern}.csv",workdir=config["workdir"], query_id=config["query_ids"],pattern=config["pattern"]),
        expand("{workdir}/results/{query_id}/8_iqtree_ancestral_scores/{query_id}_wol_param_{pattern}.csv",workdir=config["workdir"], query_id=config["query_ids"],pattern=config["pattern"]), 

include : "rules/query_fasta.smk"
include : "rules/psiblast.smk"
include : "rules/get_blasthits.smk"
include : "rules/msa.smk"
include : "rules/trim_msa.smk"
#include : "rules/ml_tree.smk"
#include : "rules/remove_gaps.smk"
include : "rules/remove_gaps_fasttree.smk"
include : "rules/msa_masking_fasttree.smk"
#include : "rules/unroot_tree.smk"
#include : "rules/raxmlng_ancestral.smk"
#include : "rules/compute_raxml_anc_score.smk"
include : "rules/unroot_fasttree.smk"
include : "rules/iqtree_anc_score.smk"
include : "rules/iq_anc.smk"
include : "rules/fasttree.smk"
