import os

configfile: "../config/config.yml"
path=config["archived_path"]

query_ids=config["query_ids"]
for query in query_ids:
        if (os.path.isdir(path+"/"+query)):
                print (query+" already computed");
                query_ids.remove(query);

print (query_ids)

rule all:
    input:
        expand("{workdir}/results/{query_id}/5_raxmlng_ancestral_scores/{query_id}_wl_param_{pattern}.csv",workdir=config["workdir"], query_id=config["query_ids"],pattern=config["pattern"]),

include : "rules/query_fasta.smk"
include : "rules/psiblast.smk"
include : "rules/get_blasthits.smk"
include : "rules/msa.smk"
include : "rules/trim_msa.smk"
include : "rules/ml_tree.smk"
include : "rules/remove_gaps.smk"
include : "rules/unroot_tree.smk"
include : "rules/raxmlng_ancestral.smk"
include : "rules/compute_raxml_anc_score.smk"
