jobs: 64 
cluster: "sbatch -A investor -p long_investor -J {rule}.job --qos long_investor --nodes=1  -t {resources.time_min} -c {resources.cpus} -o logs/cluster/{rule}_%A.out -e logs/cluster/{rule}_%A.err"
default-resources: [cpus=2, time_min=9600]
