jobs: 64 
cluster: "sbatch -p long_investor -J {rule}.job --qos long_investor --nodes=1  -t {resources.time_min} --mem={resources.mem_mb}  -c {resources.cpus} -o logs/cluster/{rule}_%A.out -e logs/cluster/{rule}_%A.err"
default-resources: [cpus=2,  mem_mb=8192, time_min=1200]
